import { ItemType } from "@/components/ProjectCard";

export const Data: ItemType[] = [
  {
    title: "myPortfolio",
    info: "A dynamic portfolio website builder that allows users to create personalized portfolios by selecting templates, customizing content, and showcasing their projects and blogs. Built with Next.js, Tailwind CSS, and Shadcn, this project offers seamless user registration, real-time preview, and publishing options, providing a comprehensive platform for building and managing online portfolios.",
    date: "August - 2024",
    images: ["/Portfolio1.jpeg", "/Portfolio2.jpeg"],
    techs: [
      "Node.js",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Resend",
    ],
    github: "https://github.com/Muhammad-Ibrahim-Dev/myPortfolio",
  },
  {
    title: "BooXtation Project",
    info: "The BooXtation Project is a robust and comprehensive online bookstore management system that addresses the needs of digital bookstores. It offers functionalities such as book, author, customer, and order management to streamline operations and improve user experience.",
    date: "October - 2024",
    images: ["/BooXtation1.png", "/BooXtation2.png"],
    techs: [
      "C#",
      "ASP.NET",
      "MVC",
      "SQL Server",
      "html",
      "css",
      "JavaScript",
      "bootstrap",
    ],
    website: "https://www.canva.com/design/DAGUU06pMyw/kAyGnO8-pqL537OLEBj5Fw/view?utm_content=DAGUU06pMyw&utm_campaign=designshare&utm_medium=link&utm_source=editor",
    github: "https://github.com/Muhammad-Ibrahim-Dev/BooXtation",
  },
  {
    title: "Postpeak | Blogging Platform",
    info: "Postpeak is a dynamic blogging platform built with Next.js and Prisma. Users can sign up, log in, create posts, view other posts, comment on them, and filter posts by category. This application provides a user-friendly interface for managing and exploring blog content.",
    date: "July - 2023",
    images: ["/blog-pc.png", "/blog-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "JavaScript",
      "NextAuth",
      "Firebase",
      "MongoDB",
      "Prisma",
    ],
    github: "",
  },

  {
    title: "Online Shoping",
    info: "An e-commerce platform designed to offer a seamless online shopping experience. The project features a responsive design with intuitive navigation, enabling users to browse products, add items to their cart, and proceed to checkout. Built using HTML, CSS, JavaScript, and Bootstrap, it ensures compatibility across various devices and browsers.",
    date: "December - 2023",
    images: ["/OnlineShoping1.jpeg", "/OnlineShoping2.jpeg"],
    techs: [
      "html",
      "csss",
      "JavaScript",
      "bootstrap",
    ],
    website: "https://muhammad-ibrahim-dev.github.io/OnlineShoping/",
    github: "https://github.com/Muhammad-Ibrahim-Dev/OnlineShoping",
  },
  {
    title: "E-commerce Application",
    info: "This React application is designed as the frontend interface for an e-commerce platform. It allows users to interact with product listings, perform searches, apply filters, and complete purchases. The design emphasizes a seamless and engaging user experience.",
    date: "December - 2022",
    images: ["/eco-pc.png", "/eco-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS"],
    github: "",
  },
  {
    title: "University system",
    info: "A comprehensive university management system developed to streamline academic and administrative processes. This system includes features for student enrollment, course management, and faculty coordination. Built using Node.js, React.js, TailwindCSS, and React Router, it provides a user-friendly interface and efficient navigation to enhance the user experience.",
    date: "June - 2022",
    images: ["/University1.jpeg", "/University2.jpeg"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS", "React router"],
    github: "https://github.com/Muhammad-Ibrahim-Dev/Karl-University",
  },
];
